from __future__ import annotations


def test_postgres_sql_uses_named_database_placeholders():
    from lib import database

    assert database.postgres_sql('SELECT * FROM books WHERE id=? AND status=?') == (
        'SELECT * FROM books WHERE id=%s AND status=%s'
    )


def test_postgres_schema_preserves_activity_order_and_single_active_session():
    from lib import schema

    ddl = schema.POSTGRES_SCHEMA
    assert 'position BIGINT GENERATED BY DEFAULT AS IDENTITY' in ddl
    assert 'CREATE UNIQUE INDEX IF NOT EXISTS one_active_reading' in ddl
    assert "WHERE state IN ('running','stopped')" in ddl


def test_database_url_is_constructed_from_supabase_pooler_environment(monkeypatch):
    from lib import database

    monkeypatch.delenv('BOOK_BUTLER_DATABASE_URL', raising=False)
    monkeypatch.setenv('SUPABASE_DB_HOST', 'pooler.example.test')
    monkeypatch.setenv('SUPABASE_DB_PORT', '6543')
    monkeypatch.setenv('SUPABASE_DB_USER', 'postgres.example')
    monkeypatch.setenv('SUPABASE_DB_PASSWORD', 'secret')
    monkeypatch.setenv('SUPABASE_DB_NAME', 'postgres')

    assert database.database_url_from_env() == (
        'postgresql://postgres.example:secret@pooler.example.test:6543/postgres?sslmode=require'
    )


def test_activity_position_uses_explicit_column_for_postgres():
    from lib import database

    class PostgresConnection:
        backend = 'postgres'

    assert database.activity_position(PostgresConnection()) == 'position'


def test_postgres_transaction_uses_advisory_lock_for_single_reading_timer():
    from lib import database

    events = []

    class Transaction:
        def __enter__(self):
            events.append('begin')
        def __exit__(self, *_):
            events.append('end')

    class PostgresConnection:
        backend = 'postgres'
        def transaction(self):
            return Transaction()
        def execute(self, query, params=()):
            events.append(query)

    with database.transaction(PostgresConnection(), lock_reading=True):
        events.append('work')

    assert events == [
        'begin',
        "SELECT pg_advisory_xact_lock(hashtext('bookbutler:reading-session'))",
        'work',
        'end',
    ]
