from __future__ import annotations

import math


def test_postgres_sql_uses_named_database_placeholders():
    from lib import database

    assert database.postgres_sql('SELECT * FROM books WHERE id=? AND status=?') == (
        'SELECT * FROM books WHERE id=%s AND status=%s'
    )


def test_postgres_schema_preserves_activity_order_and_single_active_session():
    from lib import schema

    ddl = schema.POSTGRES_SCHEMA
    assert 'position BIGINT GENERATED BY DEFAULT AS IDENTITY' in ddl
    assert 'CREATE UNIQUE INDEX IF NOT EXISTS one_active_reading' in ddl
    assert "WHERE state IN ('running','stopped')" in ddl


def test_postgres_schema_adds_reading_chunks_without_changing_activities():
    from lib import schema

    ddl = schema.POSTGRES_SCHEMA
    assert "CREATE TABLE IF NOT EXISTS reading_chunks" in ddl
    assert "source_app TEXT NOT NULL CHECK(source_app IN ('readdam', 'today-library'))" in ddl
    assert "source_ref TEXT UNIQUE" in ddl
    assert "idx_reading_chunks_duplicate" in ddl


def test_database_url_is_constructed_from_supabase_pooler_environment(monkeypatch):
    from lib import database

    monkeypatch.delenv('BOOK_BUTLER_DATABASE_URL', raising=False)
    monkeypatch.setenv('SUPABASE_DB_HOST', 'pooler.example.test')
    monkeypatch.setenv('SUPABASE_DB_PORT', '6543')
    monkeypatch.setenv('SUPABASE_DB_USER', 'postgres.example')
    monkeypatch.setenv('SUPABASE_DB_PASSWORD', 'secret')
    monkeypatch.setenv('SUPABASE_DB_NAME', 'postgres')

    assert database.database_url_from_env() == (
        'postgresql://postgres.example:secret@pooler.example.test:6543/postgres?sslmode=require'
    )


def test_activity_position_uses_explicit_column_for_postgres():
    from lib import database

    class PostgresConnection:
        backend = 'postgres'

    assert database.activity_position(PostgresConnection()) == 'position'


def test_read_frame_turns_all_null_postgres_column_into_none_not_nan():
    """quote 컬럼이 전부 NULL이면 pandas가 float64/NaN으로 추론해
    row.get('quote')가 참으로 잘못 판정되고 화면에 "nan"이 그대로
    나온다(2026-09-26 실제 데이터에서 발견). None으로 통일해 막는다."""
    from lib import database

    class Cursor:
        def fetchall(self):
            return [
                {'id': 'a', 'page': 187, 'quote': None, 'text': '4쪽을 0분 동안 읽었습니다'},
                {'id': 'b', 'page': 183, 'quote': None, 'text': '176쪽을 49분 동안 읽었습니다'},
            ]

    class PostgresConnection:
        backend = 'postgres'
        def execute(self, query, params=()):
            return Cursor()

    frame = database.read_frame(PostgresConnection(), 'SELECT * FROM activities')
    quote = frame.iloc[0]['quote']
    assert quote is None
    assert not (isinstance(quote, float) and math.isnan(quote))
    assert not quote  # row.get('quote')가 거짓으로 판정돼야 한다


def test_shelf_cover_card_does_not_crash_on_new_book_with_null_pages_from_postgres():
    """pages처럼 일부 행만 NULL인 숫자 컬럼은 Postgres 경로에서 pandas가
    float64로 승격시켜 NULL이 None이 아니라 NaN이 된다(pandas
    'future.infer_string' 아래 문자열 컬럼도 read_frame 수준에서는 NaN이
    나올 수 있어, 이 정규화는 read_frame이 아니라 사용하는 쪽에서 해야
    notebook_ui.cards()가 이미 쓰는 pd.isna() 패턴과 dtype 보존이 둘 다
    지켜진다). NaN인 pages는 `book['pages'] or 0`에서 참으로 판정돼
    total=NaN이 되고, 새 카테고리로 책을 등록한 뒤 책장(이어서 읽기)에서
    st.progress(nan)이 StreamlitAPIException으로 운영 장애를 일으켰다
    (2026-09-28 실제 발생). shelf_ui._cover_card가 직접 정규화해서 막는다."""
    from lib import shelf_ui, database

    class Cursor:
        def fetchall(self):
            return [{
                'id': 'new', 'title': '분별력 테스트 도서', 'category': '분별력',
                'current_page': 0, 'pages': None, 'cover_photo': None, 'cover_url': None,
            }]

    class PostgresConnection:
        backend = 'postgres'
        def execute(self, query, params=()):
            return Cursor()

    frame = database.read_frame(PostgresConnection(), 'SELECT * FROM books')
    book = frame.iloc[0]
    shelf_ui._cover_card(book, lambda *a, **k: None, prefix='resume', show_progress=True)


def test_postgres_transaction_uses_advisory_lock_for_single_reading_timer():
    from lib import database

    events = []

    class Transaction:
        def __enter__(self):
            events.append('begin')
        def __exit__(self, *_):
            events.append('end')

    class PostgresConnection:
        backend = 'postgres'
        def transaction(self):
            return Transaction()
        def execute(self, query, params=()):
            events.append(query)

    with database.transaction(PostgresConnection(), lock_reading=True):
        events.append('work')

    assert events == [
        'begin',
        "SELECT pg_advisory_xact_lock(hashtext('bookbutler:reading-session'))",
        'work',
        'end',
    ]
