"""비파괴적 추가 스키마. 기존 기록과 사진 파일을 보존한다."""
from __future__ import annotations

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS books (
    id TEXT PRIMARY KEY, title TEXT NOT NULL, author TEXT, publisher TEXT, isbn TEXT,
    subtitle TEXT, translator TEXT, category TEXT, pages INTEGER, current_page INTEGER,
    rating INTEGER, status TEXT, read_count INTEGER, start_date BIGINT, finish_date BIGINT,
    cover_photo TEXT, cover_url TEXT
);
CREATE TABLE IF NOT EXISTS activities (
    id TEXT PRIMARY KEY,
    position BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    book_id TEXT NOT NULL REFERENCES books(id), kind INTEGER NOT NULL CHECK (kind BETWEEN 0 AND 7),
    text TEXT, quote TEXT, page INTEGER, date BIGINT NOT NULL, photo TEXT,
    visibility TEXT NOT NULL DEFAULT 'private', pages_read INTEGER, minutes_read DOUBLE PRECISION,
    event_type TEXT, seconds_read BIGINT, base_page INTEGER, deleted_at BIGINT, updated_at BIGINT
);
CREATE TABLE IF NOT EXISTS photo_manifest (filename TEXT PRIMARY KEY, type TEXT NOT NULL, book_id TEXT, record_ids TEXT);
CREATE TABLE IF NOT EXISTS source_book_state (book_id TEXT PRIMARY KEY, raw_status INTEGER, raw_reading_now INTEGER, inferred_status TEXT, evidence TEXT);
CREATE TABLE IF NOT EXISTS app_migrations (name TEXT PRIMARY KEY, applied_at BIGINT);
CREATE TABLE IF NOT EXISTS deletion_page_effect (activity_id TEXT PRIMARY KEY, page_before INTEGER, page_after INTEGER);
CREATE TABLE IF NOT EXISTS reading_sessions (
    id TEXT PRIMARY KEY, book_id TEXT NOT NULL REFERENCES books(id), started_at BIGINT NOT NULL,
    stopped_at BIGINT, base_page INTEGER NOT NULL,
    state TEXT NOT NULL CHECK(state IN ('running','stopped','saved','cancelled')), activity_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_activities_book_id ON activities(book_id);
CREATE INDEX IF NOT EXISTS idx_activities_date ON activities(date);
CREATE INDEX IF NOT EXISTS idx_activities_kind ON activities(kind);
CREATE INDEX IF NOT EXISTS idx_books_category ON books(category);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_reading
ON reading_sessions ((1)) WHERE state IN ('running','stopped');
"""


def ensure_schema(conn):
    from lib.database import is_postgres

    if is_postgres(conn):
        for statement in POSTGRES_SCHEMA.split(';'):
            if statement.strip():
                conn.execute(statement)
        return
    if not conn.execute("SELECT 1 FROM sqlite_master WHERE name='activities'").fetchone():
        return
    columns = {r[1] for r in conn.execute('PRAGMA table_info(activities)')}
    for name, kind in [('event_type', 'TEXT'), ('seconds_read', 'INTEGER'),
                       ('base_page', 'INTEGER'), ('deleted_at', 'INTEGER'), ('updated_at', 'INTEGER')]:
        if name not in columns:
            conn.execute(f'ALTER TABLE activities ADD COLUMN {name} {kind}')
    conn.executescript('''
        CREATE TABLE IF NOT EXISTS source_book_state (
            book_id TEXT PRIMARY KEY, raw_status INTEGER, raw_reading_now INTEGER,
            inferred_status TEXT, evidence TEXT
        );
        CREATE TABLE IF NOT EXISTS app_migrations (name TEXT PRIMARY KEY, applied_at INTEGER);
        CREATE TABLE IF NOT EXISTS deletion_page_effect (
            activity_id TEXT PRIMARY KEY, page_before INTEGER, page_after INTEGER
        );
        CREATE TABLE IF NOT EXISTS reading_sessions (
            id TEXT PRIMARY KEY, book_id TEXT NOT NULL REFERENCES books(id),
            started_at INTEGER NOT NULL, stopped_at INTEGER, base_page INTEGER NOT NULL,
            state TEXT NOT NULL CHECK(state IN ('running','stopped','saved','cancelled')),
            activity_id TEXT
        );
        CREATE UNIQUE INDEX IF NOT EXISTS one_active_reading
        ON reading_sessions((1)) WHERE state IN ('running','stopped');
    ''')
    conn.commit()
